modLoader="javafml"
loaderVersion="[39,)"
license="LGPL-2.1-or-later"
issueTrackerURL="https://github.com/teaconmc/ResourceSync"

[[mods]]
modId="resource_sync"
version="${file.jarVersion}"
displayName="Resource Sync"
credits="OpenLoader by Darkhax, for IPackFinder implementation"
authors="3TUSK"
description="Preemptively keeps resource pack updated"

[[dependencies.resource_sync]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
