name: test-build
on:
  push:
    paths:
      - "src/**"
      - "build.gradle"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            **/.gradle
            !**/.gradle/libs
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Build
        run: gradle build --stacktrace
